## Problema entorno hipotesis preguntas entorno comercial entorno analitico

La variable predictora proporcionalmente insignificante por lo cual se buscara una representacion equivalente en las demas variables para reducir el dataset

# Diccionario de columnas

'trans_date_trans_time': Fecha de transaccion Hora de transaccion CAMBIAR EL DTYPE
, 'cc_num': numero de tarjeta de credito
, 'merchant': Comerciante o Vendedor
, 'category': Categoria del comerciante o transaccion
, 'amt': Monto de la transaccion
       'first': First Name los vamos a unificar con last name y determinar los unicos, eliminando duplicados o trabajando solo con unicos
       , 'last':Last Name
       , 'gender'Genero CAMBIAR A BOOLEANO df['GENDER'] = df['GENDER'].map({'Male': 1, 'Female': 0})
       , 'street': Calle podemos trabajar por ciudad o estado o codigo postal para reducir el dataframe ver que cantidades tenemos de city count
       state count street count zip count
       , 'city': Ciudad
       , 'state' Estado
       , 'zip'Codigo Postal
       , 'lat':Latitud
       'long': Longitud
       , 'city_pop': Tamaño de poblacion de la ciudad
       , 'job': Ocupacion o profesion del titular de la tarjeta
       'dob': Date of Bird Fecha de nacimiento del titular de la tarjeta, haremos una variable con la edad de todos los unicos first y last name
       , 'trans_num' ELIMINAR LOS DUPLICADOS NUMEROS UNICOS TRANSSACCIONES
       , 'unix_time': Forma de representar el tiempo lo vamos a dejar para ver las cantidades de "unique" y ver si hay horarios que se repiten con patron
       , 'merch_lat'ver si coincide con lat los eliminamos
       ,
       'merch_long'ver si coincide con LONG los eliminamos
       , 'is_fraud': 0 no fraude  1 si fraude
       '


Estos son los códigos de estado de EE. UU. que corresponden a cada abreviatura en tu lista:

NC: North Carolina
WA: Washington
ID: Idaho
MT: Montana
VA: Virginia
PA: Pennsylvania
KS: Kansas
TN: Tennessee
IA: Iowa
WV: West Virginia
FL: Florida
CA: California
NM: New Mexico
NJ: New Jersey
OK: Oklahoma
IN: Indiana
MA: Massachusetts
TX: Texas
WI: Wisconsin
MI: Michigan
WY: Wyoming
HI: Hawaii
NE: Nebraska
OR: Oregon
LA: Louisiana
DC: District of Columbia
KY: Kentucky
NY: New York
MS: Mississippi
UT: Utah
AL: Alabama
AR: Arkansas
MD: Maryland
GA: Georgia
ME: Maine
AZ: Arizona
MN: Minnesota
OH: Ohio
CO: Colorado
VT: Vermont
MO: Missouri
SC: South Carolina
NV: Nevada
IL: Illinois
NH: New Hampshire
SD: South Dakota
AK: Alaska
ND: North Dakota
CT: Connecticut
RI: Rhode Island
DE: Delaware

## DATA SET ORIGINAL (Colab-Google Drive) "**transacciones_original**"

Comenzamos con el **dataset completo** el cual deberemos reducir porque no permite Github hostearlo alli por su tamaño.- Luego de reducirlo lo transformaremos a csv y lo hostearemos en Github.-

In [202]:
#Importamos librerias necesarias
from google.colab import drive
import os
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime

In [203]:
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [204]:
#Establecemos el entorno de trabajo.
%cd '/content/gdrive/My Drive/PF_SCIENCE_I_II_III/DS_II/'

/content/gdrive/My Drive/PF_SCIENCE_I_II_III/DS_II


In [205]:
#Nombramos el dataset original y lo examinamos .
transacciones_original=pd.read_csv("Credit_Card_Transactions_DSII.csv")
transacciones_original.head(3)


Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   

                          merchant       category     amt      first     last  \
0       fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer    Banks   
1  fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie     Gill   
2             fraud_Lind-Buckridge  entertainment  220.11     Edward  Sanchez   

  gender                        street  ...      long city_pop  \
0      F                561 Perry Cove  ...  -81.1781     3495   
1      F  43039 Riley Greens Suite 393  ... -118.2105      149   
2      M      594 White Dale Suite 530  ... -112.2620     4154   

                                 job         dob  \
0          Psychologist, counselling  1988-03-09   
1  Special educational needs teacher  1978-06-21   
2        Nature conservation officer  1962-01-19   

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481   

  is_fraud  merch_zipcode  
0        0        28705.0  
1        0            NaN  
2        0        83236.0  

[3 rows x 24 columns]

In [206]:
transacciones_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 24 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   Unnamed: 0             1296675 non-null  int64  
 1   trans_date_trans_time  1296675 non-null  object 
 2   cc_num                 1296675 non-null  int64  
 3   merchant               1296675 non-null  object 
 4   category               1296675 non-null  object 
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object 
 7   last                   1296675 non-null  object 
 8   gender                 1296675 non-null  object 
 9   street                 1296675 non-null  object 
 10  city                   1296675 non-null  object 
 11  state                  1296675 non-null  object 
 12  zip                    1296675 non-null  int64  
 13  lat                    1296675 non-null  float64
 14  long              

In [207]:
#Estados únicos  en donde se realizaron transacciones del dataset original.
numero_estados_unicos = transacciones_original["state"].nunique()
print(f"El número de estados únicos es: {numero_estados_unicos}")


El número de estados únicos es: 51


In [208]:
#Total de transacciones originales.
transacciones_original.shape

(1296675, 24)

## DATASET 1ER.PROCESAMIENTO. "**transacciones_long**"

In [209]:
#Dejamos el original intacto y continuamos con "long"
transacciones_long=transacciones_original.copy()

In [210]:
#Seguimos borrando columnas innecesarias
transacciones_long.drop(['street','last','first' ], axis=1, inplace=True)


In [211]:
#Eliminamos columna redundante.
transacciones_long.drop('Unnamed: 0', axis=1, inplace=True)

In [212]:
#Observamos dtype, duplicados, nulos y dataset en gral.
transacciones_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 20 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   trans_date_trans_time  1296675 non-null  object 
 1   cc_num                 1296675 non-null  int64  
 2   merchant               1296675 non-null  object 
 3   category               1296675 non-null  object 
 4   amt                    1296675 non-null  float64
 5   gender                 1296675 non-null  object 
 6   city                   1296675 non-null  object 
 7   state                  1296675 non-null  object 
 8   zip                    1296675 non-null  int64  
 9   lat                    1296675 non-null  float64
 10  long                   1296675 non-null  float64
 11  city_pop               1296675 non-null  int64  
 12  job                    1296675 non-null  object 
 13  dob                    1296675 non-null  object 
 14  trans_num         

In [213]:
#Ademas de datos repetidos tenemos nulos en merch.
print(transacciones_long[["zip","merch_zipcode"]])

           zip  merch_zipcode
0        28654        28705.0
1        99160            NaN
2        83252        83236.0
3        59632            NaN
4        24433        22844.0
...        ...            ...
1296670  84735            NaN
1296671  21790        22630.0
1296672  88325        88351.0
1296673  57756        69367.0
1296674  59871        59870.0

[1296675 rows x 2 columns]


In [214]:
#Decidimos eliminar la columna que tiene nulos.
transacciones_long.drop('merch_zipcode', axis=1, inplace=True)

In [215]:
#Traemos estas columnas para ver los datos que contienen.
print(transacciones_long[["trans_date_trans_time","trans_num","unix_time","merch_lat","merch_long","lat","long","is_fraud"]])

        trans_date_trans_time                         trans_num   unix_time  \
0         2019-01-01 00:00:18  0b242abb623afc578575680df30655b9  1325376018   
1         2019-01-01 00:00:44  1f76529f8574734946361c461b024d99  1325376044   
2         2019-01-01 00:00:51  a1a22d70485983eac12b5b88dad1cf95  1325376051   
3         2019-01-01 00:01:16  6b849c168bdad6f867558c3793159a81  1325376076   
4         2019-01-01 00:03:06  a41d7549acf90789359a9aa5346dcb46  1325376186   
...                       ...                               ...         ...   
1296670   2020-06-21 12:12:08  440b587732da4dc1a6395aba5fb41669  1371816728   
1296671   2020-06-21 12:12:19  278000d2e0d2277d1de2f890067dcc0a  1371816739   
1296672   2020-06-21 12:12:32  483f52fe67fabef353d552c1e662974c  1371816752   
1296673   2020-06-21 12:13:36  d667cdcbadaaed3da3f4020e83591c83  1371816816   
1296674   2020-06-21 12:13:37  8f7c8e4ab7f25875d753b422917c98c9  1371816817   

         merch_lat  merch_long      lat      long  

In [216]:
#Verificamos que lat, long  y "merch_lat","merch_long" contienen los  datos muy parecidos  y decidimos eliminar las columnas.
transacciones_long.drop(["merch_lat","merch_long"], axis=1, inplace=True)

In [217]:
#Vamos a cambiar tipo de dato de variable 'dob' a tipo fecha.
transacciones_long['dob'] = pd.to_datetime(transacciones_long['dob'])
transacciones_long['dob'].dtype
print(transacciones_long['dob'])

0         1988-03-09
1         1978-06-21
2         1962-01-19
3         1967-01-12
4         1986-03-28
             ...    
1296670   1961-11-24
1296671   1979-12-11
1296672   1967-08-30
1296673   1980-08-18
1296674   1995-08-16
Name: dob, Length: 1296675, dtype: datetime64[ns]


In [218]:
#Vamos a cambiar tipo de dato de variable 'trans_date_trans_time' a tipo fecha.
transacciones_long["trans_date_trans_time"] = pd.to_datetime(transacciones_long["trans_date_trans_time"])
transacciones_long["trans_date_trans_time"].dtype
print(transacciones_long["trans_date_trans_time"])


0         2019-01-01 00:00:18
1         2019-01-01 00:00:44
2         2019-01-01 00:00:51
3         2019-01-01 00:01:16
4         2019-01-01 00:03:06
                  ...        
1296670   2020-06-21 12:12:08
1296671   2020-06-21 12:12:19
1296672   2020-06-21 12:12:32
1296673   2020-06-21 12:13:36
1296674   2020-06-21 12:13:37
Name: trans_date_trans_time, Length: 1296675, dtype: datetime64[ns]


In [219]:
#Vamos a crear columna trans_date  con función lambda para poder calcular la edad del titular de quien realiza la transacción, luego se eliminara antes de aplicar el modelo de ML.
transacciones_long['trans_date'] = transacciones_long['trans_date_trans_time'].apply(lambda x: pd.to_datetime(x).date())
print(transacciones_long['trans_date'])

0          2019-01-01
1          2019-01-01
2          2019-01-01
3          2019-01-01
4          2019-01-01
              ...    
1296670    2020-06-21
1296671    2020-06-21
1296672    2020-06-21
1296673    2020-06-21
1296674    2020-06-21
Name: trans_date, Length: 1296675, dtype: object


In [220]:
#cambiamos el tipo de dato porque en la instruccion anterior no lo tomó.
transacciones_long['trans_date'] = pd.to_datetime(transacciones_long['trans_date_trans_time'].apply(lambda x: pd.to_datetime(x).date()))
transacciones_long['trans_date'].dtype
print(transacciones_long['trans_date'])

0         2019-01-01
1         2019-01-01
2         2019-01-01
3         2019-01-01
4         2019-01-01
             ...    
1296670   2020-06-21
1296671   2020-06-21
1296672   2020-06-21
1296673   2020-06-21
1296674   2020-06-21
Name: trans_date, Length: 1296675, dtype: datetime64[ns]


In [221]:
#Vamos a crear columna   trans_time  con funcion lambda con la finalidad de determinar horarios AM PM.
transacciones_long['trans_time'] = transacciones_long['trans_date_trans_time'].apply(lambda x: pd.to_datetime(x).time())
print(transacciones_long['trans_time'])

0          00:00:18
1          00:00:44
2          00:00:51
3          00:01:16
4          00:03:06
             ...   
1296670    12:12:08
1296671    12:12:19
1296672    12:12:32
1296673    12:13:36
1296674    12:13:37
Name: trans_time, Length: 1296675, dtype: object


In [222]:
# Creamos la nueva columna 'AM_PM', luego para el modelo los transformaremos en 0(AM), 1(PM).
transacciones_long['AM_PM'] = transacciones_long['trans_time'].apply(lambda x: 'AM' if x.hour < 12 else 'PM')
print(transacciones_long[['trans_time', 'AM_PM']])

        trans_time AM_PM
0         00:00:18    AM
1         00:00:44    AM
2         00:00:51    AM
3         00:01:16    AM
4         00:03:06    AM
...            ...   ...
1296670   12:12:08    PM
1296671   12:12:19    PM
1296672   12:12:32    PM
1296673   12:13:36    PM
1296674   12:13:37    PM

[1296675 rows x 2 columns]


In [223]:
#Eliminamos la columna trans_time porque no la utilizaremos.
transacciones_long.drop('trans_time', axis=1, inplace=True)

In [224]:
# Creamos  la columna 'age' y efectuamos el calculo de los años de quien efectua la transacciÓn.
transacciones_long['age'] = transacciones_long.apply(lambda row: row['trans_date'].year - row['dob'].year - ((row['trans_date'].month, row['trans_date'].day) < (row['dob'].month, row['dob'].day)), axis=1)
print(transacciones_long[['dob', 'trans_date', 'age']])

               dob trans_date  age
0       1988-03-09 2019-01-01   30
1       1978-06-21 2019-01-01   40
2       1962-01-19 2019-01-01   56
3       1967-01-12 2019-01-01   51
4       1986-03-28 2019-01-01   32
...            ...        ...  ...
1296670 1961-11-24 2020-06-21   58
1296671 1979-12-11 2020-06-21   40
1296672 1967-08-30 2020-06-21   52
1296673 1980-08-18 2020-06-21   39
1296674 1995-08-16 2020-06-21   24

[1296675 rows x 3 columns]


In [225]:
transacciones_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 20 columns):
 #   Column                 Non-Null Count    Dtype         
---  ------                 --------------    -----         
 0   trans_date_trans_time  1296675 non-null  datetime64[ns]
 1   cc_num                 1296675 non-null  int64         
 2   merchant               1296675 non-null  object        
 3   category               1296675 non-null  object        
 4   amt                    1296675 non-null  float64       
 5   gender                 1296675 non-null  object        
 6   city                   1296675 non-null  object        
 7   state                  1296675 non-null  object        
 8   zip                    1296675 non-null  int64         
 9   lat                    1296675 non-null  float64       
 10  long                   1296675 non-null  float64       
 11  city_pop               1296675 non-null  int64         
 12  job                    12966

## SUB-DATAFRAME (basados **Fraude si/no**)

1-Trabajamos conteos y porcentajes de "**transacciones totales**".

In [226]:
#Establecemos el conteo de la variable predictora "is fraud".
transacciones_totales_conteo= transacciones_long['is_fraud'].value_counts()
transacciones_totales_conteo

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

Del 1.289.169 de transacciones totales, **7506** son **fraude**.

In [227]:
#Establecemos el procentaje.
transacciones_totales_porcentaje = transacciones_long['is_fraud'].value_counts(normalize=True) * 100
transacciones_totales_porcentaje

is_fraud
0    99.421135
1     0.578865
Name: proportion, dtype: float64

In [228]:
df_totales_porcentaje  = pd.DataFrame({'Conteo': transacciones_totales_conteo, 'Porcentaje': transacciones_totales_porcentaje})
df_totales_porcentaje = df_totales_porcentaje.round(2)
print(df_totales_porcentaje )

           Conteo  Porcentaje
is_fraud                     
0         1289169       99.42
1            7506        0.58


2-Trabajamos conteos y porcentajes de** transacciones únicas** ( en columna 'trans_num').

In [229]:
# Determinamos las transacciones unicas utilizando la columna 'trans_num'
transacciones_unicas = transacciones_long.drop_duplicates(subset=['trans_num'])
transacciones_unicas.shape

(1296675, 20)

Determinamos que **no hay** transacciones **duplicadas**.

In [230]:
#Eliminamos unix_time al conocer que no existen transacciones duplicadas
transacciones_long.drop('unix_time', axis=1, inplace=True)


3-Trabajamos para contar cuantas **transacciones** se realizaron **por cada tarjeta única** y esbtablecer un promedio de operaciones fraudulentas que evitaríamos con un  modelo predictivo.-De esa información obtendremos datos para distintos análisis previos.- Por ejemplo si las tarjetas se utilizan más de una vez para cometer fraudes.-  

## SUB-DATAFRAME (basados exclusivamente en **Fraude si**)

In [231]:
#Elegimos solo los datos que corresponden a fraude.
transacciones_fraude=transacciones_long[transacciones_long['is_fraud'] == 1]
transacciones_fraude.shape


(7506, 19)

Corroboramos el mismo nro.de transacciones fraude que con el conteo.

In [232]:
#Contamos las tarjetas únicas.
cantidad_tarjetas_unicas = transacciones_fraude['cc_num'].nunique()
print(f"Cantidad de tarjetas únicas: {cantidad_tarjetas_unicas}")

Cantidad de tarjetas únicas: 762


Se cometen **7506** transacciones fraudulentas con **762** tarjetas únicas.

In [233]:
# Agrupamos por numero de tarjeta 'cc_num', contamos  las transacciones y lo transformamos en un dataframe.-
conteo_fraude_cc= transacciones_fraude.groupby('cc_num').size().reset_index(name='fraude_count')
print(conteo_fraude_cc)


                  cc_num  fraude_count
0            60416207185             9
1            60422928733            12
2            60423098130            10
3            60427851591            14
4            60490596305            10
..                   ...           ...
757  4911818930706644725             9
758  4956828990005111019            10
759  4973530368125489546            10
760  4980323467523543940            10
761  4992346398065154184             8

[762 rows x 2 columns]


In [234]:
# Calculamos el promedio de transacciones fraudulentas por tarjeta.
promedio_fraude_cc = conteo_fraude_cc['fraude_count'].mean()
promedio_fraude_cc



9.850393700787402

In [235]:
# Formateamos el promedio con dos decimales.
promedio_formateado = f"{promedio_fraude_cc:.2f}"
print(f"El promedio de transacciones fraudulentas por tarjeta es: {promedio_formateado}")

El promedio de transacciones fraudulentas por tarjeta es: 9.85


Concluímos que en **Promedio** por cada tarjeta fraudulenta se cometen casi **10**  transacciones del mismo tenor.-

In [236]:
#Graficamos los montos de las transacciones fraudulentas



Generamos un dataframe para evaluar **montos** de transacciones por tarjeta única.

In [237]:
#Agrupamos por nro tarjeta, montos de transacciones y calculamos estadísticas.
transacciones_fraude.groupby(['cc_num'])['amt'].aggregate(['min', 'mean', 'max'])

min        mean      max
cc_num                                          
60416207185           11.74  211.081111   830.06
60422928733            7.13  625.015000  1036.43
60423098130            5.21  459.808000  1222.17
60427851591            8.86  688.985000  1164.36
60490596305           17.17  599.547000  1073.82
...                     ...         ...      ...
4911818930706644725   10.46  535.275556   951.95
4956828990005111019   11.39  659.949000  1051.26
4973530368125489546   12.84  537.107000  1018.47
4980323467523543940  289.37  720.815000  1068.34
4992346398065154184  302.91  806.565000  1091.87

[762 rows x 3 columns]

Otros dataframes para analizar otros aspectos.

In [238]:
#Agrupamos por nro. tarjeta, categorías y contamos las transcacciones.
transacciones_fraude_categoria = transacciones_fraude.groupby(['cc_num','category'])
transacciones_fraude_categoria['trans_num'].count()



cc_num               category     
60416207185          entertainment    1
                     food_dining      1
                     gas_transport    2
                     home             1
                     kids_pets        1
                                     ..
4980323467523543940  shopping_net     2
                     shopping_pos     2
4992346398065154184  grocery_pos      2
                     shopping_net     4
                     shopping_pos     2
Name: trans_num, Length: 4121, dtype: int64

Podemos inferir que realivamente **varían** en las **categorías** una misma  tarjeta fraudulenta, veremos si también varian en cuanto a "merchant"...

In [239]:
transacciones_fraude_merchant = transacciones_fraude.groupby(['cc_num','merchant'])
transacciones_fraude_merchant['trans_num'].count()

cc_num               merchant                           
60416207185          fraud_Barrows PLC                      1
                     fraud_Berge-Hills                      1
                     fraud_Cummings LLC                     1
                     fraud_Douglas-White                    1
                     fraud_Labadie LLC                      1
                                                           ..
4992346398065154184  fraud_Kerluke-Abshire                  1
                     fraud_Kihn, Abernathy and Douglas      1
                     fraud_Kris-Padberg                     1
                     fraud_Rutherford-Mertz                 1
                     fraud_Schmeler, Bashirian and Price    1
Name: trans_num, Length: 7391, dtype: int64

 Se verifican transacciones con **diferentes** **merchants** por   tarjeta fraudulenta.

In [240]:
#Vamos a determinar más profundamente otras relaciones entre transacciones y merchant.
merchant_transacciones=transacciones_fraude.groupby('merchant').count()['trans_num']
merchant_transacciones



merchant
fraud_Abbott-Rogahn                  3
fraud_Abbott-Steuber                 6
fraud_Abernathy and Sons             4
fraud_Abshire PLC                    9
fraud_Adams, Kovacek and Kuhlman     4
                                    ..
fraud_Zemlak Group                  17
fraud_Zemlak, Tillman and Cremin     2
fraud_Ziemann-Waters                 6
fraud_Zieme, Bode and Dooley         8
fraud_Zulauf LLC                     2
Name: trans_num, Length: 679, dtype: int64

In [241]:
#Nos concentramos en merchant con mas de 1 transaccion fraudulenta.
merchant_transacciones_filtradas = merchant_transacciones[merchant_transacciones > 1]
print(merchant_transacciones_filtradas)

merchant
fraud_Abbott-Rogahn                  3
fraud_Abbott-Steuber                 6
fraud_Abernathy and Sons             4
fraud_Abshire PLC                    9
fraud_Adams, Kovacek and Kuhlman     4
                                    ..
fraud_Zemlak Group                  17
fraud_Zemlak, Tillman and Cremin     2
fraud_Ziemann-Waters                 6
fraud_Zieme, Bode and Dooley         8
fraud_Zulauf LLC                     2
Name: trans_num, Length: 630, dtype: int64


In [242]:
#Visualizamos mejor en orden descendente.
merchant_transacciones_ordenadas=merchant_transacciones_filtradas.sort_values(ascending=False)
print(merchant_transacciones_ordenadas)

merchant
fraud_Rau and Sons                     49
fraud_Kozey-Boehm                      48
fraud_Cormier LLC                      48
fraud_Vandervort-Funk                  47
fraud_Kilback LLC                      47
                                       ..
fraud_Kihn, Brakus and Goyette          2
fraud_Stiedemann Ltd                    2
fraud_Kilback and Sons                  2
fraud_Kilback, Nitzsche and Leffler     2
fraud_Zulauf LLC                        2
Name: trans_num, Length: 630, dtype: int64


Con este análisis podemos ver que hay algunos comerciantes con mayores cantidades de transacciones fraudulentas....


Ahora veremos  la variacion de los **días** y **horas**,  lo cual nos indicaría que  utilizar algún instrumento rápido de bloqueo de   tarjetas sería óptimo para  evitar que se sigan haciendo transacciones con otros comerciantes. Para ello, el modelo de predicción.

In [243]:
transacciones_fraude_date = transacciones_fraude.groupby(['cc_num','trans_date_trans_time'])
transacciones_fraude_date['trans_num'].count()

cc_num               trans_date_trans_time
60416207185          2019-03-01 01:32:53      1
                     2019-03-01 02:42:25      1
                     2019-03-01 23:06:58      1
                     2019-03-02 22:10:38      1
                     2019-03-02 22:10:59      1
                                             ..
4992346398065154184  2019-10-31 23:55:45      1
                     2019-11-01 02:40:44      1
                     2019-11-01 14:55:10      1
                     2019-11-01 22:08:45      1
                     2019-11-01 22:23:48      1
Name: trans_num, Length: 7506, dtype: int64

Se advierte que el mecanismo es realizar varias transacciones el mismo día y al día siguiente también, usando  la misma tarjeta fraudulenta lo que nos hace valorar aun más un modelo que prediga en forma rápida  la predicción de fraude.-


Analizaremos columna de **gender** .

In [244]:
#Agrupamos por nro tarjeta, por gender, cantidad de transacciones .
transacciones_fraude_gender=transacciones_fraude.groupby(['cc_num',"gender"]) ['trans_num'].count().unstack(fill_value=0)
transacciones_fraude_gender

gender                F   M
cc_num                     
60416207185           9   0
60422928733           0  12
60423098130           0  10
60427851591           0  14
60490596305          10   0
...                  ..  ..
4911818930706644725   0   9
4956828990005111019   0  10
4973530368125489546  10   0
4980323467523543940   0  10
4992346398065154184   0   8

[762 rows x 2 columns]

In [245]:
# Sumamos las columnas 'F' y 'M'
total_fraude_gender= transacciones_fraude_gender.sum()
print(total_fraude_gender)

gender
F    3735
M    3771
dtype: int64


**No hay** predominancia en ningun **género** en cuanto a cantidad de transacciones fraudulentas.-
A continuacion analizamos las tarjetas únicas por city, cuantas transacciones fraudulentas efectúan.

In [246]:
#Contamos cuántas cities hay con transacciones fraudulentas.
transacciones_fraude['city'].nunique()

702

In [247]:
#Agrupamos por nro.de tarjeta y ciudad. Realizamos conteo por agrupamiento.
conteo_fraude_city= transacciones_fraude.groupby(['cc_num','city']).size().reset_index(name='count')
print(conteo_fraude_city)

                  cc_num             city  count
0            60416207185    Fort Washakie      9
1            60422928733    North Augusta     12
2            60423098130          Amorita     10
3            60427851591       Burns Flat     14
4            60490596305           Haynes     10
..                   ...              ...    ...
757  4911818930706644725             Mesa      9
758  4956828990005111019        Elizabeth     10
759  4973530368125489546          Winslow     10
760  4980323467523543940  North Haverhill     10
761  4992346398065154184          Mc Nabb      8

[762 rows x 3 columns]


In [248]:
# Calculamos el promedio de transacciones fraudulentas por tarjeta por ciudad.
promedio_fraude_city = conteo_fraude_city['count'].mean()
promedio_fraude_city

9.850393700787402

Se realizan casi **10** transacciones **por city** fraudulentas perjudicando a 10 merchants diferentes tan solo en un día, máximo  dos días.

In [249]:
#Agrupamos por nro tarjeta, por AM/PM, cantidad de transacciones.
transacciones_fraude_am_pm=transacciones_fraude.groupby(['cc_num',"AM_PM"]) ['trans_num'].count().unstack(fill_value=0)
transacciones_fraude_am_pm

AM_PM                AM  PM
cc_num                     
60416207185           2   7
60422928733           4   8
60423098130           4   6
60427851591           4  10
60490596305           3   7
...                  ..  ..
4911818930706644725   3   6
4956828990005111019   6   4
4973530368125489546   4   6
4980323467523543940   2   8
4992346398065154184   2   6

[762 rows x 2 columns]

In [250]:
# Sumamos todos los valores de la columna AM
suma_am = transacciones_fraude_am_pm['AM'].sum()
# Sumamos todos los valores de la columna PM
suma_pm = transacciones_fraude_am_pm['PM'].sum()
print(f"Suma de transacciones en AM: {suma_am}")
print(f"Suma de transacciones en PM: {suma_pm}")

Suma de transacciones en AM: 2907
Suma de transacciones en PM: 4599


Se verifica  una **marcada tendencia** a efectuar las transacciones fraudulentas en el horario **PM**.

Obtenemos las **edades** precisas de los propietarios de tarjetas únicas fraudulentas.

In [251]:
#Agrupamos por cc_num y obtenemos la edad correspondiente
age_fraude_cc = transacciones_fraude.groupby('cc_num')['age'].first().reset_index()
print(age_fraude_cc)

                  cc_num  age
0            60416207185   33
1            60422928733   77
2            60423098130   60
3            60427851591   42
4            60490596305   56
..                   ...  ...
757  4911818930706644725   78
758  4956828990005111019   38
759  4973530368125489546   53
760  4980323467523543940   72
761  4992346398065154184   63

[762 rows x 2 columns]


In [252]:
#Obtenemos estadÍsticas de las edades de los titulares de tarjetas fraudulentas
age_fraude_cc['age'].describe()


count    762.000000
mean      48.960630
std       18.690818
min       14.000000
25%       34.000000
50%       48.000000
75%       61.750000
max       93.000000
Name: age, dtype: float64

## DATASET 2DO. PROCESAMIENTO. "**transacciones_long**"

In [253]:
# Extraemos el nombre del dia y creamos una nueva columna "day_name"
transacciones_long['day_name'] = transacciones_long['trans_date_trans_time'].dt.day_name()
print(transacciones_long['day_name'])

0          Tuesday
1          Tuesday
2          Tuesday
3          Tuesday
4          Tuesday
            ...   
1296670     Sunday
1296671     Sunday
1296672     Sunday
1296673     Sunday
1296674     Sunday
Name: day_name, Length: 1296675, dtype: object


In [254]:
#Reiteramos solo los fraudes
transacciones_fraude=transacciones_long[transacciones_long['is_fraud'] == 1]

In [255]:
#Veremos los dias en donde se producen mayor cantidad de transacciones fraudulentas
conteo_fraude_day= transacciones_fraude.groupby('day_name').size().reset_index(name='days_count')
conteo_fraude_day=conteo_fraude_day.sort_values(by='days_count', ascending=False)
print(conteo_fraude_day)

    day_name  days_count
2   Saturday        1227
3     Sunday        1216
1     Monday        1182
0     Friday        1079
4   Thursday        1008
5    Tuesday         935
6  Wednesday         859


Vamos a trabajar sobre los números de las tarjetas para tratar de identificar **emisores**.

In [256]:
#Observamos las tarjetas 'unicas de las transacciones totales.
transacciones_long['cc_num']

0             2703186189652095
1                 630423337322
2               38859492057661
3             3534093764340240
4              375534208663984
                  ...         
1296670         30263540414123
1296671       6011149206456997
1296672       3514865930894695
1296673       2720012583106919
1296674    4292902571056973207
Name: cc_num, Length: 1296675, dtype: int64

In [257]:
# Creamos columna "INN" y extraemos los primeros seis dígitos (IIN)  para tener identificados diferentes emisores.
transacciones_long['IIN'] = transacciones_long['cc_num'].astype(str).str[:6].astype(int)
print(transacciones_long['IIN'])

0          270318
1          630423
2          388594
3          353409
4          375534
            ...  
1296670    302635
1296671    601114
1296672    351486
1296673    272001
1296674    429290
Name: IIN, Length: 1296675, dtype: int64


In [258]:
#Nuevamente establecemos solo las transacciones fraude.
transacciones_fraude=transacciones_long[transacciones_long['is_fraud'] == 1]

In [259]:
#Contamos los INN (emisores)únicos.
transacciones_fraude['IIN'].nunique()

748

In [260]:
#Contamos transacciones fraudes agrupadas por IIN (emisor).
conteo_fraude_por_IIN = transacciones_fraude.groupby('IIN')['trans_num'].count().reset_index()
# Renombramos la columna
conteo_fraude_por_IIN = conteo_fraude_por_IIN.rename(columns={'trans_num': 'conteo_transacciones_fraude'})
print(conteo_fraude_por_IIN)





        IIN  conteo_transacciones_fraude
0    180014                           12
1    180017                            9
2    180018                            5
3    180031                           14
4    180036                           10
..      ...                          ...
743  676308                           12
744  676309                           10
745  676326                           15
746  676327                            8
747  676372                           13

[748 rows x 2 columns]


Contamos las transacciones fraudulentas por **emisor** y a continuación las relacionaremos con **tarjetas únicas fraudulentas**.

In [261]:
# Agrupamos por 'IIN' y 'cc_num' y contamos las transacciones.
conteo_transacciones_IIN_cc = transacciones_fraude.groupby(['IIN', 'cc_num']).size().reset_index(name='conteo_transacciones')
# Ordenamos de forma descendente por el conteo de transacciones.
conteo_transacciones_IIN_cc = conteo_transacciones_IIN_cc.sort_values(by='conteo_transacciones', ascending=False)
print(conteo_transacciones_IIN_cc)

        IIN               cc_num  conteo_transacciones
513  459356        4593569795412                    19
191  352055     3520550088202337                    19
430  426012        4260128500325                    18
187  351866     3518669219150142                    16
465  440001  4400011257587661852                    16
..      ...                  ...                   ...
383  408909  4089096483689733451                     2
497  450310  4503101193493052864                     2
660  601110     6011109736646996                     2
367  400567     4005676619255478                     2
287  357643     3576431665303017                     2

[762 rows x 3 columns]


Podemos determinar claramente **cuales** son los  **emisores** con mayor cantidad de emision de tarjetas con las que efectuarán **fraudes**.-


In [262]:
# Agrupamos por 'city_pop' (poblacion de ciudad) y contamos las transacciones.
transacciones_fraude_poblacion = transacciones_fraude.groupby('city_pop')['trans_num'].count().reset_index()
# Renombramos la columna
print(transacciones_fraude_poblacion)

     city_pop  trans_num
0          23          6
1          37          9
2          46         12
3          47          6
4          49         14
..        ...        ...
686   1577385         23
687   1595797         25
688   2383912          9
689   2504700         10
690   2906700         39

[691 rows x 2 columns]


In [263]:
transacciones_fraude_poblacion.describe()

city_pop   trans_num
count  6.910000e+02  691.000000
mean   7.374887e+04   10.862518
std    2.593203e+05    4.523360
min    2.300000e+01    2.000000
25%    8.080000e+02    8.000000
50%    3.032000e+03   10.000000
75%    1.923100e+04   13.000000
max    2.906700e+06   39.000000

In [264]:
transacciones_fraude_poblacion.sample(10)

city_pop  trans_num
269      1686         10
583     69793          8
417      5438         11
652    333497         12
462      7987         11
241      1423         10
658    413574         27
6          52         12
382      4290         12
240      1420         15

Observamos que **no** **necesariamente** en poblaciones más grandes se efectúan mayores transacciones . Pero en este sample encontramos que en una población pequeña se efectuaron muchas mas transacciones fraudulentas de las que se producen en una ciudad con poblacion mayor.

Por último vamos a trabajar con un dataset reducido en forma proporcional, en primer término para poder hostearlo en Github, en segundo término, porque son en proporción, muy pocas las transacciones fraudulentas comparadas con las que se desarrollan normalmente, pero nuestro objetivo es alcanzar al máximo las posibilidades de predecir estos pocos casos .

## DATASET 3ER. PROCESAMIENTO (REDUCIDO PARA GITHUB). "**transacciones_short**"

In [265]:
#Volvemos a filtramos las filas donde is_fraud == 1 (por si hubo cambios).
transacciones_fraude = transacciones_long[transacciones_long['is_fraud'] == 1]

In [266]:
# Filtramos las filas donde is_fraud == 0 para ir armando muestra reducida
transacciones_no_fraude = transacciones_long[transacciones_long['is_fraud'] == 0]

In [267]:
# Limitamos el número de filas no fraudulentas a 8000
max_no_fraudulentas = 8000

In [268]:
#Corroboramos la cantidad de filas fraudulentas, todas formarán parte del nuevo dataset.
num_transacciones_fraude = len(transacciones_fraude)
print("Número de transacciones fraudulentas:", num_transacciones_fraude)

Número de transacciones fraudulentas: 7506


In [269]:
# Creamos un dataframe vacío para almacenar las transacciones  no fraudulentas
muestra_transacciones_no_fraudulentas= pd.DataFrame()


In [270]:
# Calculamos el número de transacciones por estado para que no superen las 8000.
num_states = transacciones_no_fraude['state'].nunique()
muestra_por_estado = max_no_fraudulentas // num_states

In [271]:
#Corroboramos el nro de states únicos de transacciones fraudulentas
count_states_unicos_fraude=transacciones_fraude["state"].unique()
print(f"El número de estados únicos es: {count_states_unicos_fraude}")

El número de estados únicos es: ['NC' 'TX' 'PA' 'AK' 'MO' 'AR' 'OH' 'VA' 'NY' 'FL' 'SD' 'ME' 'NE' 'AL'
 'CA' 'TN' 'IN' 'IA' 'UT' 'SC' 'MI' 'ND' 'KY' 'WI' 'IL' 'OK' 'DC' 'MN'
 'LA' 'OR' 'WY' 'NM' 'GA' 'KS' 'WV' 'MD' 'NH' 'AZ' 'WA' 'CO' 'NJ' 'MA'
 'DE' 'ID' 'MS' 'CT' 'MT' 'VT' 'NV' 'RI' 'HI']


Advertimos que la **diferencia** entre **states únicos** (51) totales y states unicos solo fraudes es cero.-Es decir los states únicos han sufrido al menos una vez transacciones fraudulentas.-

In [272]:
# Iteraramos sobre cada state y tomamos una muestra aleatoria de filas no fraudulentas.
for state in transacciones_no_fraude['state'].unique():
    estado_transacciones_no_fraude = transacciones_no_fraude[transacciones_no_fraude['state'] == state]
    muestra_estado_transacciones_no_fraude = estado_transacciones_no_fraude.sample(n=min(muestra_por_estado,len(estado_transacciones_no_fraude)), random_state=42)
    muestra_transacciones_no_fraudulentas = pd.concat([muestra_transacciones_no_fraudulentas,  muestra_estado_transacciones_no_fraude])

In [273]:
#Controlamos que las rows no superen las 8000.
if len(muestra_transacciones_no_fraudulentas ) >max_no_fraudulentas:
    muestra_transacciones_no_fraudulentas = muestra_transacciones_no_fraudulentas.sample(n=max_no_fraudulentas, random_state=42)

In [274]:
# Combinamos ambos subconjuntos.
transacciones_short = pd.concat([transacciones_fraude,  muestra_transacciones_no_fraudulentas])
print(transacciones_short.info())

<class 'pandas.core.frame.DataFrame'>
Index: 15506 entries, 2449 to 920853
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   trans_date_trans_time  15506 non-null  datetime64[ns]
 1   cc_num                 15506 non-null  int64         
 2   merchant               15506 non-null  object        
 3   category               15506 non-null  object        
 4   amt                    15506 non-null  float64       
 5   gender                 15506 non-null  object        
 6   city                   15506 non-null  object        
 7   state                  15506 non-null  object        
 8   zip                    15506 non-null  int64         
 9   lat                    15506 non-null  float64       
 10  long                   15506 non-null  float64       
 11  city_pop               15506 non-null  int64         
 12  job                    15506 non-null  object        
 13  do

In [275]:
transacciones_short.shape

(15506, 21)

Este es nuestro **nuevo dataset** que formatearemos como csv listo para subir a Github por si fuera requerido.Además es el dataset al cual le aplicaremos el modelo de predicción.

In [276]:
transacciones_short.head(3)

trans_date_trans_time           cc_num                          merchant  \
2449   2019-01-02 01:06:37    4613314721966            fraud_Rutherford-Mertz   
2472   2019-01-02 01:47:29  340187018810220  fraud_Jenkins, Hauck and Friesen   
2523   2019-01-02 03:05:23  340187018810220            fraud_Goodwin-Nitzsche   

           category     amt gender           city state    zip      lat  ...  \
2449    grocery_pos  281.06      M  Collettsville    NC  28611  35.9946  ...   
2472  gas_transport   11.52      F    San Antonio    TX  78208  29.4400  ...   
2523    grocery_pos  276.31      F    San Antonio    TX  78208  29.4400  ...   

      city_pop                       job        dob  \
2449       885            Soil scientist 1988-09-15   
2472   1595797  Horticultural consultant 1960-10-28   
2523   1595797  Horticultural consultant 1960-10-28   

                             trans_num is_fraud  trans_date AM_PM age  \
2449  e8a81877ae9a0a7f883e15cb39dc4022        1  2019-01-02    AM  30   
2472  bc7d41c41103877b03232f03f1f8d3f5        1  2019-01-02    AM  58   
2523  b98f12f4168391b2203238813df5aa8c        1  2019-01-02    AM  58   

       day_name     IIN  
2449  Wednesday  461331  
2472  Wednesday  340187  
2523  Wednesday  340187  

[3 rows x 21 columns]

In [277]:
transacciones_short.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15506 entries, 2449 to 920853
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   trans_date_trans_time  15506 non-null  datetime64[ns]
 1   cc_num                 15506 non-null  int64         
 2   merchant               15506 non-null  object        
 3   category               15506 non-null  object        
 4   amt                    15506 non-null  float64       
 5   gender                 15506 non-null  object        
 6   city                   15506 non-null  object        
 7   state                  15506 non-null  object        
 8   zip                    15506 non-null  int64         
 9   lat                    15506 non-null  float64       
 10  long                   15506 non-null  float64       
 11  city_pop               15506 non-null  int64         
 12  job                    15506 non-null  object        
 13  do

Probamos el paso del dataframe a csv, de csv a Github y de Github a Colab.

In [278]:
transacciones_short=pd.DataFrame(transacciones_short)
transacciones_short.to_csv('transacciones_short.csv', index=False)

In [279]:
#Vemos que el traspaso de github a colab es correcto. Empezaremos a trabajar este dataset para los modelos.
df=pd.read_csv('https://raw.githubusercontent.com/Gimena2024/transacciones_short/refs/heads/main/transacciones_short.csv')
df

trans_date_trans_time            cc_num  \
0       2019-01-02 01:06:37     4613314721966   
1       2019-01-02 01:47:29   340187018810220   
2       2019-01-02 03:05:23   340187018810220   
3       2019-01-02 03:38:03     4613314721966   
4       2019-01-02 03:55:47   340187018810220   
...                     ...               ...   
15501   2019-12-23 21:00:45  4633065159406313   
15502   2019-02-09 08:23:11  4633065159406313   
15503   2019-05-18 23:00:16  4633065159406313   
15504   2020-05-17 05:12:34  4633065159406313   
15505   2019-12-30 20:20:42  4633065159406313   

                               merchant        category      amt gender  \
0                fraud_Rutherford-Mertz     grocery_pos   281.06      M   
1      fraud_Jenkins, Hauck and Friesen   gas_transport    11.52      F   
2                fraud_Goodwin-Nitzsche     grocery_pos   276.31      F   
3                fraud_Erdman-Kertzmann   gas_transport     7.03      M   
4                    fraud_Koepp-Parker     grocery_pos   275.73      F   
...                                 ...             ...      ...    ...   
15501             fraud_Bahringer Group  health_fitness    93.56      F   
15502                fraud_Bernhard Inc   gas_transport    43.82      F   
15503            fraud_Rutherford-Mertz     grocery_pos    70.76      F   
15504         fraud_Ledner-Pfannerstill   gas_transport    66.99      F   
15505                  fraud_Fisher Inc    shopping_net  1024.21      F   

                city state    zip      lat  ...  city_pop  \
0      Collettsville    NC  28611  35.9946  ...       885   
1        San Antonio    TX  78208  29.4400  ...   1595797   
2        San Antonio    TX  78208  29.4400  ...   1595797   
3      Collettsville    NC  28611  35.9946  ...       885   
4        San Antonio    TX  78208  29.4400  ...   1595797   
...              ...   ...    ...      ...  ...       ...   
15501     Providence    RI   2908  41.8383  ...    203571   
15502     Providence    RI   2908  41.8383  ...    203571   
15503     Providence    RI   2908  41.8383  ...    203571   
15504     Providence    RI   2908  41.8383  ...    203571   
15505     Providence    RI   2908  41.8383  ...    203571   

                            job         dob                         trans_num  \
0                Soil scientist  1988-09-15  e8a81877ae9a0a7f883e15cb39dc4022   
1      Horticultural consultant  1960-10-28  bc7d41c41103877b03232f03f1f8d3f5   
2      Horticultural consultant  1960-10-28  b98f12f4168391b2203238813df5aa8c   
3                Soil scientist  1988-09-15  397894a5c4c02e3c61c784001f0f14e4   
4      Horticultural consultant  1960-10-28  7863235a750d73a244c07f1fb7f0185a   
...                         ...         ...                               ...   
15501         Nurse, children's  1995-11-29  a037b465e4488b12b2e215231a9038bd   
15502         Nurse, children's  1995-11-29  5078a3bfd06817875cbf3bdb9195c77e   
15503         Nurse, children's  1995-11-29  4a8cd67cd0ce49d66bdef0960b3f4e52   
15504         Nurse, children's  1995-11-29  7cd2d1d0e9ab3d81ccfb96f3d046c8ed   
15505         Nurse, children's  1995-11-29  4284722c1b9987b2ed3ad2016a1be20a   

      is_fraud  trans_date AM_PM age   day_name     IIN  
0            1  2019-01-02    AM  30  Wednesday  461331  
1            1  2019-01-02    AM  58  Wednesday  340187  
2            1  2019-01-02    AM  58  Wednesday  340187  
3            1  2019-01-02    AM  30  Wednesday  461331  
4            1  2019-01-02    AM  58  Wednesday  340187  
...        ...         ...   ...  ..        ...     ...  
15501        0  2019-12-23    PM  24     Monday  463306  
15502        0  2019-02-09    AM  23   Saturday  463306  
15503        0  2019-05-18    PM  23   Saturday  463306  
15504        0  2020-05-17    AM  24     Sunday  463306  
15505        0  2019-12-30    PM  24     Monday  463306  

[15506 rows x 21 columns]

###

# FEATURE SELECTION